name: publish
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'index.js'
      - 'src/**'
      - 'package.json'
      - 'functions.json'
      - 'README.md'
jobs:
  # scan code using CodeQL
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language:
          - 'javascript'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
  publish:
    runs-on: ubuntu-latest
    needs: [analyze]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - uses: actions/setup-node@v1
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org/
    - name: Publish to NPM
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
