name: upload
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'easy-use/**'
      - 'package.json'
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: Build archive
      run: bash .github/workflows/scripts/build-archive.sh
    - name: Upload files to S3 bucket
      uses: kaskadi/action-s3cp@master
      env:
        AWS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_KEY_SECRET: ${{ secrets.AWS_KEY_SECRET }}
